# Generated by Django 5.0.3 on 2024-03-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('adress', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=300)),
            ],
        ),
    ]
