# Generated by Django 5.0.3 on 2024-03-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateOrders',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_des', models.CharField(max_length=500)),
                ('timespam', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
