# Generated by Django 5.0.3 on 2024-03-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_updateorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateorders',
            old_name='update_des',
            new_name='update_desc',
        ),
    ]
